import { useEffect, useState } from 'react';
import { api, apiError } from '@/lib/api';

type User={id:string;nationalId:string;fullName:string|null;phone:string|null;email:string|null;city:string|null;completed:boolean;isActive:boolean;updatedAt:string};
type Stats={total:number;completed:number;incomplete:number};
export default function RegistryAdminPage(){
 const [stats,setStats]=useState<Stats>({total:0,completed:0,incomplete:0}); const [items,setItems]=useState<User[]>([]); const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [loading,setLoading]=useState(true); const [importing,setImporting]=useState(false); const [report,setReport]=useState<any>(null); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const [s,u]=await Promise.all([api.get('/registry/admin/stats'),api.get('/registry/admin/users',{params:{search,page,pageSize:15}})]);setStats(s.data);setItems(u.data.items);setPages(u.data.pages)}catch(e){setError(apiError(e))}finally{setLoading(false)}}; useEffect(()=>{void load()},[page,search]);
 async function importFile(file:File){setImporting(true);setReport(null);try{const fd=new FormData();fd.append('file',file);const {data}=await api.post('/registry/admin/import',fd,{headers:{'Content-Type':'multipart/form-data'}});setReport(data);await load()}catch(e){setError(apiError(e,'تعذر استيراد الملف.'))}finally{setImporting(false)}}
 async function download(path:string,name:string){try{const r=await api.get(path,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}catch(e){setError(apiError(e))}}
 return <div dir="rtl" className="space-y-6">
  <div><p className="text-sm font-bold text-primary-700">الإدارة</p><h1 className="text-2xl font-black text-slate-900">سجل المستخدمين</h1></div>
  <div className="grid gap-4 sm:grid-cols-3">{[['إجمالي أرقام الهويات',stats.total],['المكتملة',stats.completed],['غير المكتملة',stats.incomplete]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-900">{value}</p></div>)}</div>
  <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-black">استيراد أرقام الهويات</h2><p className="mt-1 text-xs text-slate-500">يدعم xlsx و xls، ويمنع تكرار الهوية.</p></div><div className="flex flex-wrap gap-2"><label className="cursor-pointer rounded-xl bg-primary-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-800">{importing?'جارٍ الاستيراد...':'رفع ملف Excel'}<input hidden type="file" accept=".xlsx,.xls" disabled={importing} onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label><button onClick={()=>download('/registry/admin/template','national-id-template.xlsx')} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">تحميل نموذج Excel</button></div></div>{report&&<div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">تمت القراءة: {report.read} — تمت الإضافة: {report.added} — مكررة: {report.duplicates} — غير صالحة: {report.invalid}</div>}</section>
  <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><h2 className="font-black">المستخدمون</h2><div className="flex flex-wrap gap-2"><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="بحث بالهوية أو الاسم" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm outline-none focus:border-primary-500"/><button onClick={()=>download('/registry/admin/export','registry-users.xlsx')} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">تصدير الكل</button><button onClick={()=>download('/registry/admin/export?completed=true','registry-users-completed.xlsx')} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">المكتمل فقط</button><button onClick={()=>download('/registry/admin/export?completed=false','registry-users-incomplete.xlsx')} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">غير المكتمل</button></div></div>
  {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b bg-slate-50 text-right text-xs text-slate-500"><th className="p-3">رقم الهوية</th><th>الاسم</th><th>الهاتف</th><th>حالة البيانات</th><th>آخر تحديث</th><th>الإجراءات</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-8 text-center text-slate-400">جارٍ التحميل...</td></tr>:items.length===0?<tr><td colSpan={6} className="p-8 text-center text-slate-400">لا توجد بيانات</td></tr>:items.map(u=><tr key={u.id} className="border-b last:border-0"><td className="p-3 font-bold" dir="ltr">{u.nationalId}</td><td>{u.fullName||'—'}</td><td dir="ltr">{u.phone||'—'}</td><td><span className={u.completed?'rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700':'rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700'}>{u.completed?'مكتملة':'غير مكتملة'}</span></td><td>{new Date(u.updatedAt).toLocaleString('ar')}</td><td><button onClick={async()=>{try{await api.patch('/registry/admin/users/'+u.id+'/active',{isActive:!u.isActive});await load()}catch(e){setError(apiError(e))}}} className="text-xs font-bold text-primary-700">{u.isActive?'تعطيل':'تفعيل'}</button>{' '}<button onClick={async()=>{if(!confirm('حذف هذا السجل؟'))return;try{await api.delete('/registry/admin/users/'+u.id);await load()}catch(e){setError(apiError(e))}}} className="text-xs font-bold text-red-600">حذف</button></td></tr>)}</tbody></table></div>
  <div className="flex items-center justify-between pt-3 text-sm"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">السابق</button><span>صفحة {page} من {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">التالي</button></div></section>
 </div>
}
