-- CreateExamSections: Insert the 30 Quranic sections (Juz' 1 to 30)
-- These sections define the exam progression for students

INSERT INTO "ExamSection" ("id", "code", "name", "order", "pagesCount", "minScore", "isRequired", "description", "isActive", "createdAt") VALUES
  (gen_random_uuid(), 'JUZ-30', 'الجزء 30', 1, 20, 60, true, 'اختبار حفظ وإتقان الجزء 30 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-29', 'الجزء 29', 2, 20, 60, true, 'اختبار حفظ وإتقان الجزء 29 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-28', 'الجزء 28', 3, 20, 60, true, 'اختبار حفظ وإتقان الجزء 28 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-27', 'الجزء 27', 4, 20, 60, true, 'اختبار حفظ وإتقان الجزء 27 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-26', 'الجزء 26', 5, 20, 60, true, 'اختبار حفظ وإتقان الجزء 26 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-25', 'الجزء 25', 6, 20, 60, true, 'اختبار حفظ وإتقان الجزء 25 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-24', 'الجزء 24', 7, 20, 60, true, 'اختبار حفظ وإتقان الجزء 24 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-23', 'الجزء 23', 8, 20, 60, true, 'اختبار حفظ وإتقان الجزء 23 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-22', 'الجزء 22', 9, 20, 60, true, 'اختبار حفظ وإتقان الجزء 22 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-21', 'الجزء 21', 10, 20, 60, true, 'اختبار حفظ وإتقان الجزء 21 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-20', 'الجزء 20', 11, 20, 60, true, 'اختبار حفظ وإتقان الجزء 20 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-19', 'الجزء 19', 12, 20, 60, true, 'اختبار حفظ وإتقان الجزء 19 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-18', 'الجزء 18', 13, 20, 60, true, 'اختبار حفظ وإتقان الجزء 18 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-17', 'الجزء 17', 14, 20, 60, true, 'اختبار حفظ وإتقان الجزء 17 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-16', 'الجزء 16', 15, 20, 60, true, 'اختبار حفظ وإتقان الجزء 16 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-15', 'الجزء 15', 16, 20, 60, true, 'اختبار حفظ وإتقان الجزء 15 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-14', 'الجزء 14', 17, 20, 60, true, 'اختبار حفظ وإتقان الجزء 14 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-13', 'الجزء 13', 18, 20, 60, true, 'اختبار حفظ وإتقان الجزء 13 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-12', 'الجزء 12', 19, 20, 60, true, 'اختبار حفظ وإتقان الجزء 12 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-11', 'الجزء 11', 20, 20, 60, true, 'اختبار حفظ وإتقان الجزء 11 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-10', 'الجزء 10', 21, 20, 60, true, 'اختبار حفظ وإتقان الجزء 10 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-09', 'الجزء 9', 22, 20, 60, true, 'اختبار حفظ وإتقان الجزء 9 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-08', 'الجزء 8', 23, 20, 60, true, 'اختبار حفظ وإتقان الجزء 8 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-07', 'الجزء 7', 24, 20, 60, true, 'اختبار حفظ وإتقان الجزء 7 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-06', 'الجزء 6', 25, 20, 60, true, 'اختبار حفظ وإتقان الجزء 6 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-05', 'الجزء 5', 26, 20, 60, true, 'اختبار حفظ وإتقان الجزء 5 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-04', 'الجزء 4', 27, 20, 60, true, 'اختبار حفظ وإتقان الجزء 4 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-03', 'الجزء 3', 28, 20, 60, true, 'اختبار حفظ وإتقان الجزء 3 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-02', 'الجزء 2', 29, 20, 60, true, 'اختبار حفظ وإتقان الجزء 2 من القرآن الكريم', true, NOW()),
  (gen_random_uuid(), 'JUZ-01', 'الجزء 1', 30, 20, 60, true, 'اختبار حفظ وإتقان الجزء 1 من القرآن الكريم', true, NOW());
